"""add screenshot

Revision ID: abc912617f9a
Revises: cb32e6d68b89
Create Date: 2026-06-02 01:59:16.829719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc912617f9a'
down_revision: Union[str, Sequence[str], None] = 'cb32e6d68b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('final_url', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('screenshot_uuid', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'screenshot_uuid')
    op.drop_column('tickets', 'final_url')
    # ### end Alembic commands ###
