"""change username value

Revision ID: cb32e6d68b89
Revises: ed5ebeeb8fcd
Create Date: 2026-06-02 01:34:09.556965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb32e6d68b89'
down_revision: Union[str, Sequence[str], None] = 'ed5ebeeb8fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tickets_fullname_key'), 'tickets', type_='unique')
    op.drop_constraint(op.f('tickets_sender_email_key'), 'tickets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('tickets_sender_email_key'), 'tickets', ['sender_email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tickets_fullname_key'), 'tickets', ['fullname'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
