"""add admin decision

Revision ID: ed5ebeeb8fcd
Revises: acea596a69db
Create Date: 2026-05-31 00:54:33.406209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed5ebeeb8fcd'
down_revision: Union[str, Sequence[str], None] = 'acea596a69db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        sa.Enum('phising', 'legit', name='admindecision').create(bind, checkfirst=True)
    op.add_column('tickets', sa.Column('admin_decision', sa.Enum('phising', 'legit', name='admindecision'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'admin_decision')
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        sa.Enum('phising', 'legit', name='admindecision').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
